apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fuse-control-plane
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/proxy-body-size: '256k'
    nginx.ingress.kubernetes.io/proxy-connect-timeout: '5'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '30'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - fuse.example.com
      secretName: fuse-control-plane-tls
  rules:
    - host: fuse.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fuse-control-plane
                port:
                  name: http
