apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fuse-system
resources:
  - namespace.yaml
  - service-account.yaml
  - config-map.yaml
  - detector-policy-config-map.yaml
  - deployment.yaml
  - pod-disruption-budget.yaml
  - idempotency-cleanup-cronjob.yaml
  - service.yaml
  - ingress.yaml
  - network-policy.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: fuse
      app.kubernetes.io/managed-by: kustomize
images:
  - name: ghcr.io/vedant817/fuse-control-plane
    newTag: 0.1.0
