apiVersion: v1
kind: ServiceAccount
metadata:
  name: fuse-control-plane
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fuse-control-plane-migration
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fuse-control-plane-maintenance
automountServiceAccountToken: false
